In [1]:
%pip install pandas streamlit plotly openpyxl

Requirement already satisfied: pandas in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Collecting streamlit
  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: plotly in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (6.5.0)
Requirement already satisfied: openpyxl in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (1.9.0)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (8.2.1)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging>=20 in c:\users\user\appdata\roaming\python\python313\site-packages (from streamlit) (25.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (11.2.1)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (6.33.0)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-23.0.1-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: requests<3,>=2.27 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\user\appdata\roaming\python\python313\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from plotly) (2.12.0)
Requirement already satisfied: et-xmlfile in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: jinja2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python313\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-0.30.0-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.1 MB 5.4 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.1 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.1 MB 5.3 MB/s eta 0:00:02
   ----------------- ---------------------- 3.9/9.1 MB 5.3 MB/s eta 0:00:01
   ---------------------- ----------------- 5.0/9.1 MB 5.2 MB/s eta 0:00:01
   --------------------------- ------------ 6.3/9.1 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.1/9.1 MB 5.2 MB/s eta 0:00:01
   ---------------------------------- ----- 7.9/9.1 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 8.7/9.1 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  8.9/9.1 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 4.1 MB/s eta 0:00:00
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---------------------------------------  786.4/795.4 kB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 795.4/795.4 kB 3.3 MB/s eta 0:00:00
Downloading cachetools-7.0.5-py3-none-any.whl (13 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Downloading pyarrow-23.0.1-cp313-cp313-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.5 MB 4.5 MB/s eta 0:00:06
   -- ------------------------------------- 1.6/27.5 MB 4.0 MB/s eta 0:00:07
   --- ------------------------------------ 2.6/27.5 MB 4.3 MB/s eta 0:00:06
   ---- ----------------------------------- 3.1/27.5 MB 3.9 MB/s eta 0:00:07
   ---- ----------------------------------- 3.4/27.5 MB 3.8 MB/s eta 0:00:07
   ----- ---------------------------------- 3.9/27.5 MB 3.2 MB/s eta 0:00:08
   ------ --------------------------------- 4.5/27.5 MB 3.2 MB/s eta 0:00:08
   ------- -------------------------------- 5.0/27.5 MB 3.1 MB/s eta 0:00:08
   -------- ------------------------------- 5.8/27.5 MB 3.1 MB/s eta 0:00:07
   --------- ------------------------------ 6.6/27.5 MB 3.2 MB/s eta 0:00:07
   --------- ------------------------------ 6.8/27.5 MB 3.2 MB/s eta 0:00:07
   ---------- ----------------------------- 7.3/27.5 MB 3.0 MB/s eta 0:00:07
   ----------- ---------------------------- 8.1/27.5 MB 3.0 MB/s eta 0:00:07
   ------------ --------------------------- 8.4/27.5 MB 3.0 MB/s eta 0:00:07
   ------------ --------------------------- 8.9/27.5 MB 2.9 MB/s eta 0:00:07
   ------------- -------------------------- 9.4/27.5 MB 2.9 MB/s eta 0:00:07
   -------------- ------------------------- 10.2/27.5 MB 2.9 MB/s eta 0:00:06
   --------------- ------------------------ 10.7/27.5 MB 3.0 MB/s eta 0:00:06
   --------------- ------------------------ 11.0/27.5 MB 2.8 MB/s eta 0:00:06
   ----------------- ---------------------- 11.8/27.5 MB 2.9 MB/s eta 0:00:06
   ------------------ --------------------- 12.6/27.5 MB 2.9 MB/s eta 0:00:06
   ------------------ --------------------- 12.8/27.5 MB 2.9 MB/s eta 0:00:06
   ------------------- -------------------- 13.1/27.5 MB 2.8 MB/s eta 0:00:06
   ------------------- -------------------- 13.4/27.5 MB 2.7 MB/s eta 0:00:06
   -------------------- ------------------- 14.2/27.5 MB 2.8 MB/s eta 0:00:05
   --------------------- ------------------ 14.9/27.5 MB 2.8 MB/s eta 0:00:05
   ---------------------- ----------------- 15.5/27.5 MB 2.8 MB/s eta 0:00:05
   ----------------------- ---------------- 16.0/27.5 MB 2.8 MB/s eta 0:00:05
   ----------------------- ---------------- 16.3/27.5 MB 2.8 MB/s eta 0:00:05
   ------------------------ --------------- 17.0/27.5 MB 2.8 MB/s eta 0:00:04
   ------------------------- -------------- 17.8/27.5 MB 2.8 MB/s eta 0:00:04
   -------------------------- ------------- 18.4/27.5 MB 2.8 MB/s eta 0:00:04
   --------------------------- ------------ 19.1/27.5 MB 2.8 MB/s eta 0:00:03
   ---------------------------- ----------- 19.9/27.5 MB 2.8 MB/s eta 0:00:03
   ----------------------------- ---------- 20.2/27.5 MB 2.8 MB/s eta 0:00:03
   ------------------------------ --------- 20.7/27.5 MB 2.8 MB/s eta 0:00:03
   ------------------------------ --------- 21.2/27.5 MB 2.8 MB/s eta 0:00:03
   ------------------------------- -------- 22.0/27.5 MB 2.8 MB/s eta 0:00:02
   --------------------------------- ------ 22.8/27.5 MB 2.8 MB/s eta 0:00:02
   --------------------------------- ------ 23.3/27.5 MB 2.8 MB/s eta 0:00:02
   ----------------------------------- ---- 24.4/27.5 MB 2.9 MB/s eta 0:00:02
   ------------------------------------ --- 25.2/27.5 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 25.7/27.5 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 26.5/27.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 2.9 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/6.9 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.9 MB 1.7 MB/s eta 0:00:04
   ------ --------------------------------- 1.0/6.9 MB 2.0 MB/s eta 0:00:03
   ------------ --------------------------- 2.1/6.9 MB 2.8 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/6.9 MB 3.2 MB/s eta 0:00:02
   ------------------- -------------------- 3.4/6.9 MB 3.1 MB/s eta 0:00:02
   ------------------------ --------------- 4.2/6.9 MB 3.0 MB/s eta 0:00:01
   ------------------------ --------------- 4.2/6.9 MB 3.0 MB/s eta 0:00:01
   --------------------------- ------------ 4.7/6.9 MB 2.7 MB/s eta 0:00:01
   ------------------------------ --------- 5.2/6.9 MB 2.7 MB/s eta 0:00:01
   --------------------------------- ------ 5.8/6.9 MB 2.7 MB/s eta 0:00:01
   ------------------------------------ --- 6.3/6.9 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 6.9/6.9 MB 2.7 MB/s eta 0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.30.0-cp313-cp313-win_amd64.whl (240 kB)
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Installing collected packages: watchdog, toml, tenacity, smmap, rpds-py, pyarrow, cachetools, attrs, referencing, pydeck, gitdb, jsonschema-specifications, gitpython, jsonschema, altair, streamlit
Successfully installed altair-6.0.0 attrs-26.1.0 cachetools-7.0.5 gitdb-4.0.12 gitpython-3.1.46 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 pyarrow-23.0.1 pydeck-0.9.1 referencing-0.37.0 rpds-py-0.30.0 smmap-5.0.3 streamlit-1.56.0 tenacity-9.1.4 toml-0.10.2 watchdog-6.0.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

df = pd.read_excel(
    "DATA DASHBOARD HRD PT ALDZAMA.xlsx",
    sheet_name="INTERNSHIP",
    skiprows=2,     # karena mulai dari baris 3
    usecols="B:L"   # sesuaikan jumlah kolom kamu
)

df.columns = [
    "nama", "program", "institusi", "kota", "ket",
    "permohonan", "penempatan", "durasi",
    "status", "final_project", "potensi"
]

df.head()

,nama,program,institusi,kota,ket,permohonan,penempatan,durasi,status,final_project,potensi
0,Rizka Aulya,Bisnis Digital,Universitas Negeri Surabaya,Surabaya,Kuliah,2025-08-01,HR,25 Agustus - 31 Desember 2025,Onboard,Dashboard HRD & Manual Book Onboarding,NaN
1,Bilal Ramadhan,Teknologi Informasi,Universitas Negeri Surabaya,Surabaya,Kuliah,2025-09-01,Exim,15 Sept 2025 - 15 Januari 2026,Selesai,NaN,NaN
2,Razeh Nurebikasyahaq,Teknologi Rekayasa Manufaktur,ITS,Surabaya,Kuliah,2025-12-01,Engineer,13 Desember 2025 - 22 Februari 2026,Selesai,Dashboard Fleet Management for Maintenance Mon...,NaN
3,Fatya Zahidah,PKK,USK,Banda Aceh,Kuliah,2025-12-01,Sales,23 Desember 2025 - 23 Januari 2026,Onboard,NaN,NaN
4,Achmad Hardinata,Teknik Permesinan,SMK Nurul Islam,Gresik,SMK,2026-01-01,Fabrikasi,05 Januari 2026 - 30 Juni 2026,Onboard,NaN,NaN

In [2]:
# ubah permohonan jadi datetime
df['permohonan'] = pd.to_datetime(df['permohonan'], errors='coerce')

# ambil bulan
df['bulan'] = df['permohonan'].dt.to_period('M').astype(str)

In [3]:
# 1. jumlah per institusi
institusi = df['institusi'].value_counts().reset_index()
institusi.columns = ['institusi', 'jumlah']

# 2. permohonan per bulan
permohonan = df['bulan'].value_counts().sort_index().reset_index()
permohonan.columns = ['bulan', 'jumlah']

# 3. status intern
status = df['status'].value_counts().reset_index()
status.columns = ['status', 'jumlah']

In [1]:
import pandas as pd

FILE_PATH = "DATA DASHBOARD HRD PT ALDZAMA.xlsx"

# BACA DATA
df = pd.read_excel(
    FILE_PATH,
    sheet_name="MAN POWER",
    usecols="B:H"
)

# RENAME KOLOM
df.columns = [
    "nama",
    "jenis_kelamin",
    "jabatan",
    "branch",
    "group_project",
    "ring",
    "status_kontrak"
]

# LIHAT DATA
df.head()

,nama,jenis_kelamin,jabatan,branch,group_project,ring,status_kontrak
0,Agus Jayana,NaN,DIREKSI,HO,Head Office,NaN,Permanent
1,Hendar Sulaeman,NaN,DIREKSI,HO,Head Office,NaN,Permanent
2,Muhammad Achyad,NaN,DIREKSI,HO,Head Office,NaN,Permanent
3,"Zulkarnaini, ST",NaN,DIREKSI,HO,Head Office,NaN,Permanent
4,Rizky Hidayat,NaN,DIREKSI,HO,Head Office,NaN,Permanent

In [2]:
df['jabatan'] = df['jabatan'].astype(str).str.strip()
df['branch'] = df['branch'].astype(str).str.strip()
df['group_project'] = df['group_project'].astype(str).str.strip()
df['status_kontrak'] = df['status_kontrak'].astype(str).str.strip().str.lower()

In [3]:
total = len(df)
permanent = len(df[df['status_kontrak'] == 'permanent'])
kontrak = len(df[df['status_kontrak'] == 'kontrak'])

print(total, permanent, kontrak)

570 33 286

In [4]:
df['jabatan'].value_counts()

jabatan
nan                          231
HELPER                        51
STAFF                         44
OPERATOR                      31
Helper                        21
Semi skill                    17
SUPERVISOR/LEADER/ADVISOR     15
Skill brick                   12
Scaffolder                     9
Driver                         9
Vacuum Operator                7
Electrical Technician          6
Supervisor Project             6
MANAGER                        6
Safety Officer                 6
Mechanical Technician          6
DIREKSI                        6
Shift Engineer                 5
Admin Project                  5
Helper Scaffolder              5
DRIVER                         5
Operator Excavator             4
Vacuum Truck Driver            4
Instrument Technician          4
Mentor Tapper Skimmer          4
Dump Truck Driver              4
Safety officer                 4
Foreman                        3
Skill Brick Layer              3
Safety                         3
Material Control               2
Site Manager                   2
Safety Refractory              2
Advisor                        2
SUPPORTING                     2
welder                         2
Demolish                       1
PJO                            1
Team Leader Scaffolding        1
Admin                          1
Driver Scaffolder              1
Admin Scaffolding              1
Admin Safety                   1
Safety Koordinator             1
fitter                         1
technical engineer             1
Staff Exim                     1
Staff                          1
Staff Admin                    1
Safety Representatif           1
Semi Skill                     1
Opr. forklift                  1
Fitter                         1
Fitter/Semi Skill              1
Safety Representative          1
Administrator                  1
Mekanik                        1
Driver Light Vehicle           1
Name: count, dtype: int64

In [5]:
df['branch'].value_counts()

branch
HO                                 112
Aldzama - Refractory                86
Aldzama-Antam Lining                85
Aldzama - HOTMETAL                  55
Aldzama-Vale                        44
Aldzama-Antam Electrode Casing      33
HO/Fabrikasi Site&WS                23
Aldzama - Scaffolding               21
Aldzama - Lime Package              19
Aldzama - Excavator & DT Rental     17
Aldzama-Vacuum PTFI                 16
HO/Hydraulic                        12
Aldzama-CMP                         11
Aldzama-Vacuum Antam                10
Aldzama-Smelting ASD & Others        9
Aldzama - Tapper Skimmer             4
HO/Security                          4
Aldzama - Safety Signage             3
HO - Fabrikasi                       2
Aldzama - Komodo PTFI                2
HO / Hydraulic                       1
HO / Fabrikasi                       1
Name: count, dtype: int64

In [6]:
df['group_project'].value_counts()

group_project
PT Freeport Indonesia       225
Head Office                 153
PT ANTAM                    128
PT Vale Indonesia            44
PT Ceria Metalindo Prima     11
PT SMELTING                   9
Name: count, dtype: int64

In [7]:
df['status_kontrak'].value_counts()

status_kontrak
kontrak      286
nan          251
permanent     33
Name: count, dtype: int64